import { apiClient } from '@/services/api'

export type AssistanceStatus = 'PENDING' | 'APPROVED' | 'REJECTED' | 'PAID' | 'CANCELLED'
interface AssistanceDto { ID: string; UserID: string; AmountRequested: string; Reason: string; Description?: string; AttachmentURL?: string; Status: AssistanceStatus; AmountApproved?: string; ReviewedBy?: string; ReviewedAt?: string; RejectionReason?: string; AmountDisbursed?: string; DisbursementMethod?: string; DisbursementReference?: string; DisbursedAt?: string; CreatedAt: string; UpdatedAt: string; member_name?: string; member_email?: string }
export interface AssistanceRequest { id: string; userId: string; memberName?: string; memberEmail?: string; amountRequested: string; reason: string; description?: string; attachmentUrl?: string; status: AssistanceStatus; amountApproved?: string; reviewedAt?: string; rejectionReason?: string; amountDisbursed?: string; disbursementMethod?: string; disbursementReference?: string; disbursedAt?: string; createdAt: string }
const map = (value: AssistanceDto): AssistanceRequest => ({ id: value.ID, userId: value.UserID, memberName: value.member_name, memberEmail: value.member_email, amountRequested: value.AmountRequested, reason: value.Reason, description: value.Description, attachmentUrl: value.AttachmentURL, status: value.Status, amountApproved: value.AmountApproved, reviewedAt: value.ReviewedAt, rejectionReason: value.RejectionReason, amountDisbursed: value.AmountDisbursed, disbursementMethod: value.DisbursementMethod, disbursementReference: value.DisbursementReference, disbursedAt: value.DisbursedAt, createdAt: value.CreatedAt })
export async function listMyAssistanceRequests() { const { data } = await apiClient.get<{ data: AssistanceDto[] }>('/assistance-requests/'); return data.data.map(map) }
export async function listAdminAssistanceRequests(status?: AssistanceStatus) { const { data } = await apiClient.get<{ data: AssistanceDto[] }>('/admin/assistance-requests/', { params: { status } }); return data.data.map(map) }
export async function createAssistanceRequest(input: { amountRequested: string; reason: string; description?: string; attachmentUrl?: string }) { const { data } = await apiClient.post<{ data: AssistanceDto }>('/assistance-requests/', { amount_requested: input.amountRequested, reason: input.reason, description: input.description || undefined, attachment_url: input.attachmentUrl || undefined }); return map(data.data) }
export async function approveAssistanceRequest(id: string, amountApproved: string) { await apiClient.post(`/assistance-requests/${id}/approve`, { amount_approved: amountApproved }) }
export async function rejectAssistanceRequest(id: string, reason: string) { await apiClient.post(`/assistance-requests/${id}/reject`, { reason }) }
export async function payAssistanceRequest(id: string, input: { amount: string; method: string; reference: string }) { await apiClient.post(`/assistance-requests/${id}/pay`, input) }
