import { useState } from 'react'
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { FundTable } from '@/components/shared/FundTable'
import { PageHeader } from '@/components/shared/PageHeader'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { useApp } from '@/context/AppContext'
import { contributionPlans, contributions, fundGrowth, loans, members, repayments } from '@/data/social-fund-data'

const personal = (rows: string[][]) => rows.filter((row) => row[0] === 'Bonheur Ishimwe')
function DataPage({ title, description, columns, rows, action }: { title: string; description: string; columns: string[]; rows: string[][]; action?: string }) {
  return <div><PageHeader title={title} description={description} action={action ? <Button className="rounded-full">{action}</Button> : undefined} /><FundTable columns={columns} rows={rows} /></div>
}
export const MembersPage = () => <DataPage title="Members" description="Manage Social Fund membership and account status" action="Add Member" columns={['Member ID','Full Name','Email','Phone','Status','Joined']} rows={members} />
export const ContributionPlansPage = () => <DataPage title="Contribution Plans" description="Recurring contribution commitments for all members" action="Create Plan" columns={['Member','Amount','Frequency','Start Date','End Date','Next Due Date','Status']} rows={contributionPlans} />
export const ContributionsPage = () => <DataPage title="Contributions" description="Track expected and received member contributions" action="Record Contribution" columns={['Member','Expected','Paid','Due Date','Payment Date','Method','Reference','Status']} rows={contributions} />
export const LoansPage = () => <DataPage title="Loans" description="Review the fund's complete loan portfolio" action="New Loan" columns={['Member','Requested Amount','Requested Date','Approved Amount','Outstanding','Status','Approved By']} rows={loans} />
export const RepaymentsPage = () => <DataPage title="Loan Repayments" description="Monitor scheduled and completed repayments" columns={['Member','Loan','Expected','Paid','Due Date','Payment Date','Status']} rows={repayments} />
export const MemberContributionsPage = () => <DataPage title="My Contributions" description="Your complete contribution history" columns={['Member','Expected','Paid','Due Date','Payment Date','Method','Reference','Status']} rows={personal(contributions)} />
export const MemberPlanPage = () => <DataPage title="My Contribution Plan" description="Your current recurring contribution commitment" columns={['Member','Amount','Frequency','Start Date','End Date','Next Due Date','Status']} rows={personal(contributionPlans)} />
export const MemberLoansPage = () => <DataPage title="My Loans" description="Your loan applications and balances" action="Request Loan" columns={['Member','Requested Amount','Requested Date','Approved Amount','Outstanding','Status','Approved By']} rows={personal(loans)} />
export const MemberRepaymentsPage = () => <DataPage title="My Repayments" description="Your upcoming and completed loan repayments" columns={['Member','Loan','Expected','Paid','Due Date','Payment Date','Status']} rows={personal(repayments)} />

export function ApprovalsPage() { return <div><PageHeader title="Approvals" description="Requests waiting for administrator review" /><div className="grid gap-3 lg:grid-cols-3">{[['Loan Request','Eric Niyonzima · RWF 800,000'],['Contribution Change','Aline Mukamana · RWF 30,000/month'],['Member Request','Patrick Habimana · New membership']].map(([title,detail]) => <Card key={title}><CardHeader><CardTitle>{title}</CardTitle><CardDescription>{detail}</CardDescription></CardHeader><CardContent className="flex gap-2"><Button size="sm">Approve</Button><Button size="sm" variant="outline">Review</Button></CardContent></Card>)}</div></div> }
export function ReportsPage() { const summary = [['Total Contributions','RWF 12,480,000'],['Outstanding Loans','RWF 4,250,000'],['Repayment Performance','94.2%'],['Fund Growth','+12.8%']]; return <div><PageHeader title="Reports" description="Fund performance and member contribution insights" action={<Button className="rounded-full">Export Report</Button>} /><div className="mb-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{summary.map(([label,value]) => <Card key={label}><CardContent className="p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-xl font-bold">{value}</p></CardContent></Card>)}</div><Card><CardHeader><CardTitle>Fund Growth</CardTitle><CardDescription>Total balance over the last six months</CardDescription></CardHeader><CardContent><div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={fundGrowth}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="month" /><YAxis tickFormatter={(value) => `${value / 1000000}m`} /><Tooltip formatter={(value) => `RWF ${Number(value).toLocaleString()}`} /><Bar dataKey="value" fill="#0F9D58" radius={[8,8,0,0]} /></BarChart></ResponsiveContainer></div></CardContent></Card></div> }
export function NotificationsPage() { const { notifications, markNotificationRead, markAllNotificationsRead } = useApp(); return <div><PageHeader title="Notifications" description="Fund activity, reminders, and account updates" action={<Button variant="outline" className="rounded-full" onClick={markAllNotificationsRead}>Mark all read</Button>} /><Card><CardContent className="divide-y p-0">{notifications.map((n) => <button key={n.id} type="button" onClick={() => markNotificationRead(n.id)} className="block w-full p-4 text-left hover:bg-muted"><div className="flex justify-between gap-4"><p className="text-sm font-semibold">{n.title}</p><span className="text-xs text-muted-foreground">{n.time}</span></div><p className="mt-1 text-sm text-muted-foreground">{n.message}</p></button>)}</CardContent></Card></div> }
export function AuditLogsPage() { return <DataPage title="Audit Logs" description="Trace important administrative and account activity" columns={['Date & Time','Administrator','Action','Resource','IP Address']} rows={[["27 Aug 2026, 09:42","Grace Uwera","Approved loan","LN-1049","10.0.0.24"],["26 Aug 2026, 16:10","Bonheur Ishimwe","Updated contribution plan","SF-001","10.0.0.18"],["25 Aug 2026, 11:05","System","Marked contribution overdue","TXN-88502","Internal"]]} /> }
export function ProfilePage({ admin = false }: { admin?: boolean }) { const { currentUser } = useApp(); const [name,setName] = useState(currentUser?.fullName ?? ''); return <div><PageHeader title={admin ? 'Settings' : 'Profile'} description="Manage your account information and preferences" /><div className="grid gap-3 lg:grid-cols-2"><Card><CardHeader><CardTitle>Personal Information</CardTitle><CardDescription>Details supplied to the Social Fund</CardDescription></CardHeader><CardContent className="space-y-4"><div><Label htmlFor="name">Full Name</Label><Input id="name" value={name} onChange={(e) => setName(e.target.value)} /></div><div><Label htmlFor="email">Email</Label><Input id="email" value={currentUser?.email ?? ''} readOnly /></div><Button>Save Changes</Button></CardContent></Card><Card><CardHeader><CardTitle>Account</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p><span className="text-muted-foreground">Member ID:</span> {currentUser?.id}</p><p><span className="text-muted-foreground">Role:</span> {currentUser?.role}</p><p><span className="text-muted-foreground">Status:</span> Active</p></CardContent></Card></div></div> }
