import { Bell, CalendarDays, HandCoins, Users, WalletCards } from 'lucide-react'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { FundTable } from '@/components/shared/FundTable'
import { PageHeader } from '@/components/shared/PageHeader'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { contributions, fundGrowth, repayments } from '@/data/social-fund-data'

function Metrics({ items }: { items: Array<[string,string,string]> }) { const icons = [WalletCards, Users, HandCoins, CalendarDays]; return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{items.map(([label,value,detail], i) => { const Icon = icons[i % icons.length]; return <Card key={label}><CardContent className="flex items-start justify-between p-4"><div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-xl font-bold">{value}</p><p className="mt-1 text-[11px] text-muted-foreground">{detail}</p></div><span className="rounded-xl bg-accent p-2 text-primary"><Icon className="h-4 w-4" /></span></CardContent></Card>})}</div> }
export function AdminDashboardPage() { return <div className="space-y-3"><PageHeader title="Admin Dashboard" description="Social Fund performance and operations overview" /><Metrics items={[["Total Fund Balance","RWF 19,750,000","+12.8% this year"],["Total Members","124","118 active plans"],["Outstanding Loans","RWF 4,250,000","18 active loans"],["Pending Requests","7","3 require attention"]]} /><div className="grid gap-3 lg:grid-cols-5"><Card className="lg:col-span-3"><CardHeader><CardTitle>Monthly Contributions</CardTitle><CardDescription>Fund growth through August 2026</CardDescription></CardHeader><CardContent><div className="h-56"><ResponsiveContainer width="100%" height="100%"><AreaChart data={fundGrowth}><defs><linearGradient id="fund" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#0F9D58" stopOpacity={.3}/><stop offset="1" stopColor="#0F9D58" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month"/><YAxis tickFormatter={(v) => `${v/1000000}m`}/><Tooltip formatter={(v) => `RWF ${Number(v).toLocaleString()}`}/><Area dataKey="value" stroke="#0F9D58" fill="url(#fund)" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></CardContent></Card><Card className="lg:col-span-2"><CardHeader><CardTitle>Fund Health</CardTitle></CardHeader><CardContent className="space-y-4">{[["Monthly contributions","RWF 2,145,000"],["Overdue contributions","RWF 85,000"],["Overdue repayments","RWF 120,000"],["Active plans","118"]].map(([a,b]) => <div key={a} className="flex justify-between border-b pb-3 text-sm last:border-0"><span className="text-muted-foreground">{a}</span><strong>{b}</strong></div>)}</CardContent></Card></div><div><h2 className="mb-2 text-sm font-semibold">Recent Contributions</h2><FundTable columns={['Member','Expected','Paid','Due Date','Payment Date','Method','Reference','Status']} rows={contributions.slice(0,3)} /></div></div> }
export function MemberDashboardPage() { const personalContributions = contributions.filter((r) => r[0] === 'Bonheur Ishimwe'); const personalRepayments = repayments.filter((r) => r[0] === 'Bonheur Ishimwe'); return <div className="space-y-3"><PageHeader title="Member Dashboard" description="Welcome back, Bonheur. Here is your Social Fund overview." /><Metrics items={[["Total Contributed","RWF 480,000","Since March 2024"],["Next Contribution","RWF 20,000","Monthly plan · Active"],["Next Due Date","05 Sep 2026","9 days remaining"],["Outstanding Loan","RWF 150,000","Loan status · Active"]]} /><div className="grid gap-3 lg:grid-cols-3"><Card className="lg:col-span-2"><CardHeader><CardTitle>Recent Contributions</CardTitle></CardHeader><CardContent className="p-0"><FundTable columns={['Member','Expected','Paid','Due Date','Payment Date','Method','Reference','Status']} rows={personalContributions} /></CardContent></Card><Card><CardHeader><CardTitle>Next Repayment</CardTitle><CardDescription>Loan LN-1031</CardDescription></CardHeader><CardContent><p className="text-2xl font-bold">RWF 25,000</p><p className="mt-1 text-sm text-muted-foreground">Due 20 Sep 2026</p><div className="mt-5 flex items-center gap-2 rounded-xl bg-accent p-3 text-sm text-primary"><Bell className="h-4 w-4" /> Reminder enabled</div></CardContent></Card></div><div><h2 className="mb-2 text-sm font-semibold">Recent Repayments</h2><FundTable columns={['Member','Loan','Expected','Paid','Due Date','Payment Date','Status']} rows={personalRepayments} /></div></div> }
